### ISSUE TITLE
Not Supported format :  package://pr2_description/meshes/base_v0/caster.stl

### ISSUE THREAD

**Issue by ghost** [jihoonl/wviz#3]
I want to ask why my browser shows this message, and cannot display the whole robot model. Thank you!

**Comment by MerAARIZOU** [comment]
put pr2_description/meshes/base_v0/caster.stl in apache server (you should install apache on any other http server on your machine), then set "path" parameter in html file to "http://localhost/" the urdf file should be visualized

**Comment by ghost** [comment]
Thanks. It is OK now. Please close this issue.
